app-banking-txn-anomaly-service:
  ports:
   - 9999:9999
  image: strawberry/app-banking-txn-anomaly
elasticsearch:
  image: elasticsearch:2.4
  container_name: elasticsearch
  environment:
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 9200:9200
   - 9300:9300
mongo:
  image: mongo:3.3
  ports:
   - 27017:27017
zookeeper:
  container_name: zookeeper
  image: jplock/zookeeper:3.4.6
  ports:
   - 2181:2181
kafka:
  image: ches/kafka
  ports:
   - 9092:9092
  environment:
   - KAFKA_ADVERTISED_HOST_NAME=$DOCKER_IP
   - KAFKA_ADVERTISED_PORT=9092
  links:
   - zookeeper:zookeeper
kibana:
  image: kibana:4.6
  ports:
   - 5601:5601
  links:
   - elasticsearch:elasticsearch
